<?php 
/**



*/
class UsersProfileCardWidgetAdminPageFramework_Form_View___CSS_ToolTip extends UsersProfileCardWidgetAdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return "th > label > span > .users-profile-card-widget-form-tooltip {margin-top: 1px;margin-left: 1em;}.users-profile-card-widget-content th > label > span > .users-profile-card-widget-form-tooltip {float: right;}.postbox-container th > label > span > .users-profile-card-widget-form-tooltip {margin-left: 1em;float: none;}.users-profile-card-widget-section-title > * > a.users-profile-card-widget-form-tooltip,.users-profile-card-widget-collapsible-title > * > a.users-profile-card-widget-form-tooltip {margin-left: 1em;}.users-profile-card-widget-section-tab a.users-profile-card-widget-form-tooltip {margin-left: 0.48em;color: #BEBEBE;vertical-align: middle;} .users-profile-card-widget-section-tab.nav-tab.active a.users-profile-card-widget-form-tooltip {color: #BEBEBE;}.users-profile-card-widget-section-title > * > a.users-profile-card-widget-form-tooltip > span,.users-profile-card-widget-collapsible-title > * > a.users-profile-card-widget-form-tooltip > span {margin-top: -4px;font-size: inherit;}.users-profile-card-widget-form-tooltip > span {font-size: 1.2em;vertical-align: middle;}.users-profile-card-widget-section-title > * > a.users-profile-card-widget-form-tooltip > span.users-profile-card-widget-form-tooltip-content,.users-profile-card-widget-collapsible-title > * > a.users-profile-card-widget-form-tooltip > span.users-profile-card-widget-form-tooltip-content,a.users-profile-card-widget-form-tooltip > .users-profile-card-widget-form-tooltip-content {font-size: 13px;font-weight: normal;}a.users-profile-card-widget-form-tooltip {vertical-align: middle;outline: none; text-decoration: none;cursor: default;color: #BEBEBE;}a.users-profile-card-widget-form-tooltip > .users-profile-card-widget-form-tooltip-content > .users-profile-card-widget-form-tooltip-title {font-weight: bold;}a.users-profile-card-widget-form-tooltip strong {line-height:30px;}a.users-profile-card-widget-form-tooltip:hover {text-decoration: none;} a.users-profile-card-widget-form-tooltip > span.users-profile-card-widget-form-tooltip-content {display: none; padding: 14px 20px 14px;margin-top: -30px; margin-left: 28px;width: 320px; line-height:16px;z-index: 100000;}a.users-profile-card-widget-form-tooltip:hover > span.users-profile-card-widget-form-tooltip-content{display: inline; position: absolute; color: #111;border:1px solid #DCA; background: #FFFFF4;margin-left: -280px;margin-top: -72px;}a.users-profile-card-widget-form-tooltip > span.users-profile-card-widget-form-tooltip-content {border-radius:4px;box-shadow: 5px 5px 8px #CCC;-webkit-box-shadow: 5px 5px 8px rgba(0, 0, 0, 0.2);-moz-box-shadow: 5px 5px 8px rgba(0, 0, 0, 0.2);box-shadow: 5px 5px 8px rgba(0, 0, 0, 0.2);}";
    }
}
