<?php 
/**



*/
class UsersProfileCardWidgetAdminPageFramework_Form_View___CSS_Section extends UsersProfileCardWidgetAdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getFormSectionRules();
    }
    private function _getFormSectionRules() {
        return ".users-profile-card-widget-section .form-table {margin-top: 0;}.users-profile-card-widget-section .form-table td label { display: inline;}.users-profile-card-widget-section-tabs-contents {margin-top: 1em;}.users-profile-card-widget-section-tabs { margin: 0;}.users-profile-card-widget-tab-content { padding: 0.5em 2em 1.5em 2em;margin: 0;border-style: solid;border-width: 1px;border-color: #dfdfdf;background-color: #fdfdfd; }.users-profile-card-widget-section-tab {background-color: transparent;vertical-align: bottom; margin-bottom: -1px;margin-left: 0px;margin-right: 0.5em;background-color: #F1F1F1;font-weight: normal;}.users-profile-card-widget-section-tab:hover {background-color: #F8F8F8;}.users-profile-card-widget-section-tab.active {background-color: #fdfdfd; }.users-profile-card-widget-section-tab h4 {margin: 0;padding: 0.4em 0.8em;font-size: 1.12em;vertical-align: middle;white-space: nowrap;display:inline-block;font-weight: normal;}.users-profile-card-widget-section-tab.nav-tab {padding: 0.2em 0.4em;}.users-profile-card-widget-section-tab.nav-tab a {text-decoration: none;color: #464646;vertical-align: inherit; outline: 0; }.users-profile-card-widget-section-tab.nav-tab a:focus { box-shadow: none;}.users-profile-card-widget-section-tab.nav-tab.active a {color: #000;}.users-profile-card-widget-content ul.users-profile-card-widget-section-tabs > li.users-profile-card-widget-section-tab {list-style-type: none;margin: -4px 4px -1px 0;}.users-profile-card-widget-repeatable-section-buttons {float: right;clear: right;margin-top: 1em;}.users-profile-card-widget-section-caption {text-align: left;margin: 0;}.users-profile-card-widget-section .users-profile-card-widget-section-title {}.users-profile-card-widget-sections.sortable-section > .users-profile-card-widget-section {padding: 1em 1.8em 1em 2.6em;}.users-profile-card-widget-sections.sortable-section > .users-profile-card-widget-section.is_subsection_collapsible {display: block; float: none;border: 0px;padding: 0;background: transparent;}.users-profile-card-widget-sections.sortable-section > .users-profile-card-widget-tab-content {display: block; float: none;border: 0px;padding: 0.5em 2em 1.5em 2em;margin: 0;border-style: solid;border-width: 1px;border-color: #dfdfdf;background-color: #fdfdfd;}.users-profile-card-widget-sections.sortable-section > .users-profile-card-widget-section {margin-bottom: 1em;}.users-profile-card-widget-section {margin-bottom: 1em; }.users-profile-card-widget-sectionset {margin-bottom: 1em; display:inline-block;width:100%;}.users-profile-card-widget-section > .users-profile-card-widget-sectionset {margin-left: 2em;}";
    }
}
